### ISSUE TITLE
Not working with resume_CN template with sharelatex?

### ISSUE THREAD

**Issue by TMAC135** [billryan/resume#11]
Right now, I am trying to modify the contends of the resume_CN in the sharelatx, but it seems that sharelatex can't show the Chinese characters. Any ideas?

**Comment by billryan** [comment]
Confirmed, I will check it later. Maybe it's the problem of new TexLive 2015 issue in ShareLaTeX.

**Comment by billryan** [comment]
It is working for my old project using Tex Live 2014 in ShareLaTeX. I will fix it for Tex Live 2015 later.

**Comment by plutoid** [comment]
我刚试了texlive2016, 需要下载4个Adobe的中文字体放到下面的目录里.

resume# ls fonts/zh_CN-Adobe/ -lh
total 57M
-rw-r--r-- 1 root root 14M Dec 10 10:30 AdobeFangsongStd-Regular.otf
-rw-r--r-- 1 root root 12M Dec 10 10:30 AdobeHeitiStd-Regular.otf
-rw-r--r-- 1 root root 17M Dec 10 10:30 AdobeKaitiStd-Regular.otf
-rw-r--r-- 1 root root 15M Dec 10 10:30 AdobeSongStd-Light.otf

然后确认打开 resume.tex 下面的选项:
\usepackage{zh_CN-Adobefonts_external} % Simplified Chinese Support using external fonts (./fonts/zh_CN-Adobe/)

**Comment by billryan** [comment]
@plutoid 估计是那段时间 ShareLaTeX 抽风，现在没问题了

**Comment by CNfreeee** [comment]
哥们。在windows下第一次编译中文版tex大概要多久？

**Comment by billryan** [comment]
@CNfreeee 第一次编译估计也就分分钟吧，这点时间应该还好，除非你简历有好几十页...

**Comment by CNfreeee** [comment]
哦哦，在windows下用ctex编译不了，换到linux下用texlive瞬间就好了，谢谢了

在 2017-02-21 19:48:38，"billryan" <notifications@github.com> 写道：


@CNfreeee 第一次编译估计也就分分钟吧，这点时间应该还好，除非你简历有好几十页...

**Comment by billryan** [comment]
@CNfreeee CTeX 我也试过的，可能是你编译方式不对，你能用 TeXlive 编译好也不错。
