### ISSUE TITLE
Trouble about catalog of output pdf

### ISSUE THREAD

**Issue by Cathon** [billryan/resume#12]
Hi, billryan. Thank you for this awesome template.
I found that there is something strange about the table of content after generating PDF file.
It is like:
- "F19D 教育背景
- "F0C0 项目经历
- "F085 技能
- "F08A 比赛经历
- "F129 其他

**Comment by billryan** [comment]
The `F19D` is the Unicode code points of fontawesome fonts, I didn't notice the toc of PDF. Maybe it's the font issue of toc, I have to check it carefully.

As a temporary solution, you can remove the fontawesome font in title to get rid of these Unicode code points in toc if you want show it on the resume.(IMOH, toc is not necessary for a resume)

**Comment by Cathon** [comment]
Actually I found there is warnings about `\section{\faGraduationCap\ 教育背景}` here. But I have no idea to fix it.
```
 Package hyperref Warning: Token not allowed in a PDF string (Unicode): removing `\char' on input line 20.
```

By the way, how to remove the index of generated PDF file?
Thanks.

**Comment by billryan** [comment]
Could you paste your resume tex file? I will check it later. I can not find the index in my pdf.

**Comment by knowncold** [comment]
I met the same problem even using the example tex.
The warnings are:
```
Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\char' on input line 21.

(/usr/local/texlive/2017/texmf-dist/tex/generic/oberdiek/se-ascii-print.def)

Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\char' on input line 27.


Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\char' on input line 66.


Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\char' on input line 74.


Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\char' on input line 78.
```

**Comment by billryan** [comment]
https://tex.stackexchange.com/questions/53513/hyperref-token-not-allowed

The warnings are related to PDF bookmark, you can pass this warning since we do not need bookmark for a resume.
