### ISSUE TITLE
add document of customising fonts

### ISSUE THREAD

**Issue by billryan** [billryan/resume#17]

**Comment by shenfei** [comment]
Hi, I tried to add "SourceHanSans.ttc" and "SourceHanSerif.ttc" in 'fonts/zh_CN-Adobe/' directory and modified the corresponding positions in 'zh_CN-Adobefonts_external.sty'. But it doesn't work out.

So, is there any documents or tips for customising fonts yet?

Thanks a lot.

**Comment by shauryachawla** [comment]
how to add a new fontawesome icon alongwith the existing email, linkedin ones? I wish to include address info as well.

**Comment by billryan** [comment]
I am on vocation these days and will add it next week.

**Comment by billryan** [comment]
@shenfei I am not sure where the `.ttc` fonts is working with XeTeX, ttf or otf should work.

@shauryachawla `\faEnvelope`, find the name of icon, and add prefix `fa`.

**Comment by billryan** [comment]
Google Noto fonts is working(`.otf`), I will add Noto Sans and Noto Serif package this weekend.

**Comment by billryan** [comment]
DONE #25
