### ISSUE TITLE
green box around the email and GiuHub

### ISSUE THREAD

**Issue by liferlisiqi** [billryan/resume#22]
Hello, billryan.
When I download the .pdf and open it in local machine, there are green box around the email and GitHub link. Have you meet this problem? I want to remove these box. Thank you!!!

**Comment by knowncold** [comment]
My pdf have the same problem and I found its reason may be `hyperref` package.
Adding `\hypersetup{hidelinks}` can fix it.

**Comment by billryan** [comment]
@knowncold Thanks. 👍 

@liferlisiqi I cannot reproduce with both TeXLive 2014 and 2017... You can paste your complie environment/method and raw tex here if still has problem.

**Comment by liferlisiqi** [comment]
I compile my resume with the online latex editor "ShareLatex" @billryan . My problem is solved by the answer provided by @knowncold . Thank you , your method is cool!

**Comment by billryan** [comment]
I compiled it with ShareLatex too but could not see green box around href links with my PDF reader(skim)... 😞
Glad to know the workaround `\hypersetup{hidelinks}` works for you.
