### ISSUE TITLE
一编译很多错误

### ISSUE THREAD

**Issue by Raise-me-up** [billryan/resume#23]
三个文件： resume-zh_CN.tex，resume_photo.tex，resume.tex
分别用 texstudio+texLive套件编译，都出现错误。
编译第一个有pdf生成，但顶部有错误；编译后两个则没有pdf生成。

编译resume-zh_CN.tex的错误如下：
Missing number, treated as zero. \progressbar@LoadFile@IfExist{tikz}
Missing = inserted for \ifnum. \progressbar@LoadFile@IfExist{tikz}
Missing number, treated as zero. \progressbar@LoadFile@IfExist{tikz}
Missing \begin{document}. \progressbar@LoadFile@IfExist{tikz}
Undefined control sequence. \progressbar@LoadFile@IfExist{tikz}
Missing number, treated as zero. ...ar@LoadFile@IfExist[2011/08/03]{kvoptions}
Missing = inserted for \ifnum. ...ar@LoadFile@IfExist[2011/08/03]{kvoptions}
Missing number, treated as zero. ...ar@LoadFile@IfExist[2011/08/03]{kvoptions}
Undefined control sequence. ...ar@LoadFile@IfExist[2011/08/03]{kvoptions}
Missing number, treated as zero. \progressbar@LoadFile@IfExist{kvsetkeys}
Missing = inserted for \ifnum. \progressbar@LoadFile@IfExist{kvsetkeys}
Missing number, treated as zero. \progressbar@LoadFile@IfExist{kvsetkeys}
Undefined control sequence. \progressbar@LoadFile@IfExist{kvsetkeys}
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. \ProcessKeyvalOptions
Undefined control sequence. \SetupKeyvalOptions
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. \AddToKeyvalOption
Undefined control sequence. \AddToKeyvalOption
Undefined control sequence. \AddToKeyvalOption
Undefined control sequence. \AddToKeyvalOption
Undefined control sequence. \AddToKeyvalOption
Undefined control sequence. ...of{I} * \real{\progressbarlocal@heightr}}
Undefined control sequence. ^^I\kvsetkeys
Missing number, treated as zero. ...eys{progressbarlocal}{heighta=\BarHeight}
Illegal unit of measure (pt inserted). ...eys{progressbarlocal}{heighta=\BarHeight}
Undefined control sequence. \AddToKeyvalOption
Undefined control sequence. \AddToKeyvalOption
Undefined control sequence. ...th{\BarHeight}{\progressbarlocal@heighta}
Missing number, treated as zero. ...th{\BarHeight}{\progressbarlocal@heighta}
Illegal unit of measure (pt inserted). ...th{\BarHeight}{\progressbarlocal@heighta}
Undefined control sequence. \AddToKeyvalOption
Undefined control sequence. ...ength{\BarWidth}{\progressbarlocal@width}
Missing number, treated as zero. ...ength{\BarWidth}{\progressbarlocal@width}
Illegal unit of measure (pt inserted). ...ength{\BarWidth}{\progressbarlocal@width}
Undefined control sequence. \AddToKeyvalOption
Undefined control sequence. ...dedCorners}{\progressbarlocal@roundnessa}
Missing number, treated as zero. ...dedCorners}{\progressbarlocal@roundnessa}
Illegal unit of measure (pt inserted). ...dedCorners}{\progressbarlocal@roundnessa}
Undefined control sequence. \AddToKeyvalOption
Undefined control sequence. ...rderWidth}{\progressbarlocal@borderwidth}
Missing number, treated as zero. ...rderWidth}{\progressbarlocal@borderwidth}
Illegal unit of measure (pt inserted). ...rderWidth}{\progressbarlocal@borderwidth}
The package tikz is older than (progressbar) but a version from or newer is required by
The package kvoptions is older than 2011/08/03(progressbar) but a version from or newer 2011/08/03 is required by
The package kvsetkeys is older than (progressbar) but a version from or newer is required by
Overfull \hbox (2552.95126pt too wide) in paragraph
Underfull \hbox (badness 10000) in paragraph
Token not allowed in a PDF string (Unicode):(hyperref) removing `\char'
Token not allowed in a PDF string (Unicode):(hyperref) removing `\char'
Token not allowed in a PDF string (Unicode):(hyperref) removing `\char'
Token not allowed in a PDF string (Unicode):(hyperref) removing `\char'
Token not allowed in a PDF string (Unicode):(hyperref) removing `\char'
Overfull \vbox (0.38379pt too high) has occurred while \output is active []

求博主详解。

**Comment by billryan** [comment]
『分别用 texstudio+texLive套件编译』把你的 TeXLive 版本说明一下，另外说一下编译方式。

用 xelatex 按理应该不会有什么问题，前提是 TeXLive 2014, 不排除新版本下的问题，我需要找一个新版的来测试重现

**Comment by Raise-me-up** [comment]
TeXLive版本是2017的，TeXstudio版本是2.12.6，默认编译器是XeLaTeX。

**Comment by billryan** [comment]
估计是 TeXLive 2017 新版本的问题，我周末找个 2017 的发行版试一下

**Comment by billryan** [comment]
测试环境：https://hub.docker.com/r/sumdoc/texlive-2017/
编译使用 XeLaTeX, 编译结果如下：

1. `xelatex resume.tex` ==> 正常输出 `resume.pdf`, 未见异常
2. `xelatex resume-zh_CN.tex` ==> 正常输出 `resume-zh_CN.pdf`, 未见异常
3. `xelatex resume_photo.tex` ==> 正常输出 `resume_photo.pdf`, 未见异常

以上三者编译均只出现 hyperhref 的 warning, 实际上对输出 PDF 没有影响，PDF 书签而已。
建议仔细检查你的编译环境，texstudio 是否有其他未知参数。

**Comment by Raise-me-up** [comment]
博主，你给的简历模板没有问题，我找到我问题的根源了。我安装的CTeX和TeXLive起冲突了。我把CTeX卸载后就没问题了。
简历模板很好，非常感谢你的贡献，给你比心~

**Comment by Ouyangyaofu** [comment]
请问这个模板是不是就不能用ctex中的xelatex编译呢？我用ctex就会出现以上问题。

**Comment by billryan** [comment]
@Ouyangyaofu Windows 下的 CTeX 官方安装的话，我以前试过是没有问题的(Windows7 + CTeX 2.9.2)

你这种问题我这无法重现，感觉是你安装或者使用的时候哪里的姿势不对 :(

**Comment by Ouyangyaofu** [comment]
![image](https://user-images.githubusercontent.com/38096494/38354569-aad4d852-38ec-11e8-90ab-8478cd204c2e.png)
老是报错，见附件！求大神帮忙解决一下

**Comment by billryan** [comment]
@Ouyangyaofu 把你的系统环境、 TeX 发行版本和编译方式贴一下

**Comment by Ouyangyaofu** [comment]
@billryan windows 10, 
![image](https://user-images.githubusercontent.com/38096494/38402517-6396477a-398f-11e8-98df-3dbedcdb1105.png)
![image](https://user-images.githubusercontent.com/38096494/38402524-6e92892c-398f-11e8-99ce-8cb020f80123.png)

**Comment by billryan** [comment]
@Ouyangyaofu 找了台 Windows 10 的机器后终于重现了，问题已修复，等会 push 最新代码，你的这个问题转移到 #19 讨论

**Comment by Ouyangyaofu** [comment]
好的，谢谢你！ @billryan
