### ISSUE TITLE
中文字体多种类型略显杂乱

### ISSUE THREAD

**Issue by Latarvin** [billryan/resume#25]
英文简历的字体感觉很统一，但是中文简历的字体包含了宋体、楷体、黑体，看起来有点杂乱，请问有没有自定义修改字体的方法？谢谢

**Comment by billryan** [comment]
看一下 https://github.com/billryan/resume/blob/master/zh_CN-Adobefonts_external.sty 替换为自己的字体文件

**Comment by billryan** [comment]
我试着移植一下 Google 思源黑体

**Comment by billryan** [comment]
刚在本地移植了 NotoSerif 中文，将 `external.sty` 的字体名改一下就能工作了，周末我会将相应的文件和包名放上来。

**Comment by Latarvin** [comment]
麻烦你了，谢谢！

**Comment by billryan** [comment]
Noto CJK 字体来源参考 [Noto CJK – Google Noto Fonts](https://www.google.com/get/noto/help/cjk/)
使用时在 tex 里指定相应包即可，如

https://github.com/billryan/resume/blob/ad4ea4ab19b7917c95fd390cd61c40c9686af0c3/resume-zh_CN.tex#L7

启用 Noto CJK Serif, 则注释掉默认使用的 `\usepackage{zh_CN-Adobefonts_external}`, 反注释 `\usepackage{NotoSerifCJKsc_external}`

如果想使用其他字体，自己参考相应的 .sty 改为自己的字体文件名

DONE ad4ea4ab19b7917c95fd390cd61c40c9686af0c3
