### ISSUE TITLE
标题前的小图标有哪些可选

### ISSUE THREAD

**Issue by AlexZhou1995** [billryan/resume#26]
默认的有
```
\faGraduationCap
\faCogs
\faInfo
```
等等，还有其他的吗。。

获奖情况是个小心心实在是太萌了，想改一下 ：）

**Comment by AlexZhou1995** [comment]
找到了，在fontawesomesymbols系列文件里。。

**Comment by daniel94104** [comment]
想知道如何自己从fontawesome添加图标？ 
试了试在fontawesomesymbols的generic 文件里添加 \def\faBlackberry{\faicon{blackberry}}，但是没有用

**Comment by billryan** [comment]
@daniel94104 晚上我更新一把，你这么添加只是引用，然而真正的字体文件中并未存在

https://github.com/billryan/resume/blob/master/fonts/fontawesome/opentype/FontAwesome.otf

**Comment by daniel94104** [comment]
@billryan  感谢感谢！

**Comment by billryan** [comment]
评估了一下，就不重复造轮子了，你直接用新的 fontawesome5 这个包吧 http://ctan.math.illinois.edu/fonts/fontawesome5/doc/fontawesome5.pdf

**Comment by daniel94104** [comment]
这个可以啊。 感谢感谢！

**Comment by xiaofami** [comment]
> 评估了一下，就不重复造轮子了，你直接用新的 fontawesome5 这个包吧 http://ctan.math.illinois.edu/fonts/fontawesome5/doc/fontawesome5.pdf

请问要如何用fontawesome5替换掉模板中默认的fontawesome包呢？想用award这个图标~直接引用fontawesome5会报错重定义，也没有找到模板文件哪里引用了fontawesome。使用的是完整版texlive，已经预装了fontawesome5。

**Comment by billryan** [comment]
@xiaofami 如果报重定义的错我估计是包冲突，你可以将项目目前已有的 fontawesome 的定义移除，我这的 texlive 版本略老不包含 fontawesome5 就不方便重现了

**Comment by zhangm365** [comment]
亲测可以使用 `fontawesome5`  这个包：在文件 `resume.cls` 中替换成 `\RequirePackage{fontawesome5}` 。
