### ISSUE TITLE
关于datesubsection的问题

### ISSUE THREAD

**Issue by xingfu12478** [billryan/resume#27]
您好， 我在resume.cls中新定义了一个datesubsection，定义如下：
\newcommand{\schooldatedsubsection}[5]{%
  \subsection[#1]{#1 \hfill #2 \hfill #3 \hfill #4 \hfill #5}%
}
但是放到latex中，写入两行五列的内容，但是编译出来的5列中，有些列不是左对齐的，请问该怎么解决呢？谢谢。

**Comment by billryan** [comment]
我晚上回去试试看

**Comment by billryan** [comment]
hfill 本身就不是左对齐的意思，指的是在水平线上尽量铺满弹开。你把你的原始内容发一下，如果要两行多列左对齐，表格的方法肯定可行
