### ISSUE TITLE
How to add the linkedin-square icon?

### ISSUE THREAD

**Issue by EVANMON** [billryan/resume#32]
I can use "\linkedin" directly but when I wanna use "\linkedin-square", the hyphen would split the word and an error is reported. So if I wanna use the linkedin-square icon, how should I call the function or package? Thanks in advance.

**Comment by billryan** [comment]
Fixed, use latest code and `\linkedinsquare`

```
\linkedinsquare[billryan8]{https://www.linkedin.com/in/billryan8}}
```
