### ISSUE TITLE
Package hyperref Warning

### ISSUE THREAD

**Issue by SpecialYang** [billryan/resume#35]
I use this code to denote education background:
```
\section{\faGraduationCap 教育背景}
```
Then, I got the following issue:
```
Package hyperref Warning: Token not allowed in a PDF string (Unicode): removing `\char' on input line 20.
```
How can I fix this problem?

**Comment by billryan** [comment]
Try to use `\texorpdfstring{\faGraduationCap 教育背景}{教育背景}`

refer: [PDF bookmark](https://tex.stackexchange.com/questions/53513/hyperref-token-not-allowed)
