### ISSUE TITLE
How to add more icons from https://fontawesome.com

### ISSUE THREAD

**Issue by tailomoon** [billryan/resume#36]
Hi billryan

Thank you for sharing your resume template. 

I am trying to add several icons which were not included in your  file fontawesomesymbols-generic.tex. Let's suppose the name of the icon is XXX with its fa unicode FYYY. I guess I need to add `\def\faXXX{\faicon{XXX}}` to fontawesomesymbols-generic.tex, and add `\expandafter\def\csnamefaicon@XXX\endcsname{{\FA\symbol{"FYYY}}}` to fontawesomesymbols-xeluatex.tex. However, I don't know how to add codes to fontawesomesymbols-pdftex.tex.

Could you please help. Thanks.

**Comment by billryan** [comment]
If you use TexLive 2018 and later, you can use `fontawesome5` package.
If you use XeLaTeX, you can try <https://github.com/billryan/latex-fontawesome5>, I will include this package as submodule for resume template this weekend.
