### ISSUE TITLE
How to adjust the size of font of resume title and first part?

### ISSUE THREAD

**Issue by SpecialYang** [billryan/resume#39]
The size of font of resume title and first part is too big. How can I make it smaller?

**Comment by billryan** [comment]
The source code of resume title(name) is at [resume.cls#L79](https://github.com/billryan/resume/blob/master/resume.cls#L79), you can replace the `\Huge` with other smaller fonts'

If you want a compact layout, you can put basic info(name, phone, email) and education background into a table environment.

e.g.

```
  \begin{table}
    \begin{tabular}{ll}
    \Large\textbf{\faAddressCard\quad 姓名} & \Large\textbf{\textbf{\faUserGraduate\quad 教育经历}} \\
    \mobile{\ (+86)  手机号} & \textbf{\faUniversity}\ \textbf{硕士学校}\qquad\quad 硕士\quad XX 专业 \quad 2013 -- 2016 \\
    \email{\ 邮箱}\qquad\quad\ & \textbf{\faUniversity}\ \textbf{本科学校}\quad 学士\quad XX 专业\qquad\qquad\ 2009 -- 2013 \\
    \end{tabular}
  \end{table}
```

Remove fontawesome font if you do not need. Such as `\faUserGraduate`.
