### ISSUE TITLE
hyperlink ugly blue border

### ISSUE THREAD

**Issue by xuuexu** [billryan/resume#42]
https://github.com/billryan/resume/blob/a37fac7ed405d99e435bb868eba3980a1c35541a/resume.cls#L12
should be modified to

`\RequirePackage[hidelinks]{hyperref} `

refer to: [Remove ugly borders around clickable cross-references and hyperlinks](https://tex.stackexchange.com/questions/823/remove-ugly-borders-around-clickable-cross-references-and-hyperlinks/824)

**Comment by xuuexu** [comment]
more user-friendly I mean

**Comment by billryan** [comment]
Good suggestion, but I think I have already set `hidelinks` with 
https://github.com/billryan/resume/blob/a37fac7ed405d99e435bb868eba3980a1c35541a/resume.cls#L13

**Comment by xuuexu** [comment]
sorry, 我傻了没看到 git repo里面有这句，我是看shareLaTex编译出来有问题, 回git搜索了一下也没有就发issue了。
