### ISSUE TITLE
font size of resume_photo.tex is bigger than resume.tex

### ISSUE THREAD

**Issue by 372046933** [billryan/resume#45]
As shown in title, the font size of the two templates are inconsistent. When printed on A4, `resume_photo.tex` has much bigger font size

**Comment by billryan** [comment]
fixed https://github.com/billryan/resume/blob/master/resume_photo.tex#L16

You can change the font size.

**Comment by 372046933** [comment]
Great! https://github.com/billryan/resume/commit/3a8393276af061320727cb4bf9d882853f4ce17a fixed it.
