### ISSUE TITLE
A bug with fonts

### ISSUE THREAD

**Issue by MIracleyin** [billryan/resume#46]
when i use zh_CN edition, the Compiler give me feedback
 {
	"resource": "/c:/Users/xxx/resume-master/resume.tex",
	"owner": "LaTeX",
	"severity": 8,
	"message": "Package fontspec: The font \"AdobeHeitiStd-Regular\" cannot be found.\n",
	"source": "LaTeX",
	"startLineNumber": 16,
	"startColumn": 1,
	"endLineNumber": 16,
	"endColumn": 65536
}
i used your old resume example about 1 years ago, but now i can't use again.
PS:all of fonts i can find in my computer
i use Win 10 ,TexLive 2019 and Compiler with VScode

**Comment by billryan** [comment]
It should work with XeLaTex, try to use xelatex compiler.

**Comment by MIracleyin** [comment]
Sorry, but I use xelatex compiler by TeXworker editor in TeXlive 2019.
And I check my font file, I have all fonts.
I try to fix the name of font in your “zh_CN-Adobefonts_external”.but it all right.
I sorry but I was confused.

发件人: billryan <notifications@github.com>
发送时间: 2019年12月29日 0:52
收件人: billryan/resume <resume@noreply.github.com>
抄送: MIracleyin <miracleyin@live.com>; Author <author@noreply.github.com>
主题: Re: [billryan/resume] A bug with fonts (#46)


It should work with XeLaTex, try to use xelatex compiler.

―

**Comment by billryan** [comment]
如果系统已经装过，可以使用
`\usepackage{zh_CN-Adobefonts_internal}`，否则使用默认的外部加载的方式

 [中英文切换
](https://github.com/billryan/resume/tree/zh_CN#%E4%B8%AD%E8%8B%B1%E6%96%87%E5%88%87%E6%8D%A2)

**Comment by MIracleyin** [comment]
我使用\usepackage{zh_CN-Adobefonts_internal}，但按照原配置还是无法成功使用。所以我使用了其他的字体。
例如“Microsoft YaHei” 将“zh_CN-Adobefonts_internal.sty”中所有出错的字体包给替换以后，成功编译，可以正常显示中文。
所以问题是，我所使用的 Win10 环境中 Adobe 字体名称和您使用的有不同吗？

**Comment by MIracleyin** [comment]
我使用\usepackage{zh_CN-Adobefonts_internal}，但按照原配置还是无法成功使用。所以我使用了其他的字体。
例如“Microsoft YaHei” 将“zh_CN-Adobefonts_internal.sty”中所有出错的字体包给替换以后，成功编译，可以正常显示中文。
所以问题是，我所使用的 Win10 环境中 Adobe 字体名称和您使用的有不同吗？

**Comment by billryan** [comment]
一般建议使用默认的 external 就够了，这个我没记错的话是按照文件名加载的，不会有问题。
internal Win10 下我这也没法测了，没有 Windows 的机器

**Comment by MIracleyin** [comment]
通过读 http://mirrors.cqu.edu.cn/CTAN/info/lshort/chinese/lshort-zh-cn.pdf 解决了我的问题
这个文件发现我之前安装的字体都没有为所有用户安装，如果还出现字体问题应该都可以这样解决。
