### ISSUE TITLE
中文镜像下载地址失效

### ISSUE THREAD

**Issue by ThyrixYang** [billryan/resume#47]
如题，github上下100m的东西根本下不下来

另外建议把模板挂在overleaf上，现在sharelatex登录直接跳转到overleaf，打不开模板

更正，在sharelatex可以打开，直接跳转到overleaf，但还是建议把模板直接放到overleaf templates里

**Comment by billryan** [comment]
1. 我会找个合适的国内链接供下载加速
2. sharelatex 被收购确实有些年头了，我周末根据 overleaf 再适配一次模板

**Comment by billryan** [comment]
1. 已经提供国内 Coding 镜像，下载应该无问题了，晚上更新文档

**Comment by billryan** [comment]
updated overleaf link with 5a3fb620fecb96acd739ad27630f55fb60759dd7
