### ISSUE TITLE
使用https://latexonline.cc/编译中文模板出错

### ISSUE THREAD

**Issue by Kxy-Moriaty** [billryan/resume#49]
您好，我在使用latexonline.cc编译resume-zh_CN.tex时如下报错：
xelatex -interaction nonstopmode -recorder -output-directory latex.out /tmp/downloads/tmp_4312/resume-zh_CN.tex
<no file>: error: Emergency stop: job aborted, file error in nonstop mode
      at <*> /tmp/downloads/tmp_4312/resume-zh_CN.tex
There were errors; /tmp/storage/compilation_1820/output.pdf not updated

请问该如何解决呢？非常感谢

**Comment by billryan** [comment]
他那个我不确定还有没有在维护，要不用 overleaf 在线编译好了，我等会更新下 overleaf 的模板地址

**Comment by billryan** [comment]
updated overleaf link with 5a3fb620fecb96acd739ad27630f55fb60759dd7
