### ISSUE TITLE
English template?

### ISSUE THREAD

**Issue by rjworks** [billryan/resume#65]
The template link to Overleaf is in Chinese. Is there English?

**Comment by v1siuol** [comment]
Yes, there is an English version in the template, but the the default one On Overleaf is `resume-zh_CH.tex`, which is the Chinese version.

You can select the `resume.tex` in the left file tree and then recompile to get the English version. 

To set the default document, click on the Overleaf menu icon above the file list, and set the "Main document" option to the .tex file you need.
